# Generated by Django 4.0.6 on 2022-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 To 1000', '100 To 1000'), ('1000 To 5000', '1000 To 5000'), ('5000 To 10000', '5000 To 10000'), ('10000 To 30000', '10000 To 30000'), ('30000 To 100000', '30000 To 100000'), ('100000 & Above', '100000 & Above')], max_length=30)),
            ],
        ),
    ]
