# Generated by Django 4.0.6 on 2022-07-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
